modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "seafoamsadditions"
version = "${version}"
displayName = "Seafoam's Additions"
authors = "SeafoamWolf"
description = '''A mod that adds in simple additions to the vanilla game.'''
#logoFile = ""

[[dependencies.seafoamsadditions]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seafoamsadditions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seafoamsadditions]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"